- 
  name: 'Demo for TSB team'
  hosts: all
  become: yes
  remote_user: ansible
  gather_facts: true
  tasks:
    - name: Install apache2
      apt: 
        name:  apache2 
        update_cache:  yes 
        state:  latest

    - name: Show SAP_SID variable
      ansible.builtin.debug:
       msg: "'{{ lookup('ansible.builtin.env', 'SAP_SID') }}' is the SAP_SID environment variable."
          
    - name: Show SAP_RELEASE variable
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'SAP_RELEASE') }}' is the SAP_RELEASE environment variable."
      
    - name: Show SAP_HA variable
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'SAP_HA') }}' is the SAP_HA environment variable."    
      
    - name: Show DB_HA variable
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'DB_HA') }}' is the DB_HA environment variable."
    
    - name: 'Copy page template to server'
      copy:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
    
    - name: 'Update J2SAP_SID with actual SAP SID'
      ansible.builtin.replace:
        path: /var/www/html/index.html
        regexp: 'J2SAP_SID'
        replace: '{{ SAP_SID }}'
