- 
  name: 'Demo for TSB team'
  hosts: all
  become: yes
  remote_user: ansible
  gather_facts: true
  tasks:
    - name: Install apache2
      apt: 
        name:  apache2 
        update_cache:  yes 
        state:  latest
        
    - debug: msg="{{ lookup('env') }} "
    
    - name: 'Copy page template to server'
      copy:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
    
    - name: 'Update J2SAP_SID with actual SAP SID'
      ansible.builtin.replace:
        path: /var/www/html/index.html
        regexp: 'J2SAP_SID'
        replace: '{{ SAP_SID }}'
