- 
  name: 'Demo for TSB team'
  hosts: all
  become: yes
  remote_user: ansible
  gather_facts: true
  tasks:
    - name: Install apache2
      apt: 
        name:  apache2 
        update_cache:  yes 
        state:  latest
  
    - name: Assign internal variables from env variables
      ansible.builtin.set_fact:
        SAPsid: "{{ lookup('env', 'SAP_SID') }}"
        DBha: "{{ lookup('env', 'DB_HA', default=false) }}"
        SAPha: "{{ lookup('env', 'SAP_HA', default=false) }}"
        SAPrelease: "{{ lookup('env', 'SAP_RELEASE') }}"
        MasterPW: "{{ lookup('env', 'MASTER_PW') }}"
      delegate_to: localhost

    - name: Create page from template
      ansible.builtin.template:
        src: "templates/index.html.j2"
        dest: "/var/www/html/index.html"
        owner: www-data
        mode: 0644
