- 
  name: 'Demo for TSB team'
  hosts: all
  become: yes
  remote_user: ansible
  gather_facts: true
  tasks:
    - name: Install apache2
      apt: 
        name:  apache2 
        update_cache:  yes 
        state:  latest

    - name: Show SAP_SID variable
      ansible.builtin.debug:
       msg: "SAP_SID:       '{{ lookup('ansible.builtin.env', 'SAP_SID') }}'"
          
    - name: Show SAP_RELEASE variable
      ansible.builtin.debug:
        msg: "SAP_RELEASE:  '{{ lookup('ansible.builtin.env', 'SAP_RELEASE') }}'"
      
    - name: Show SAP_HA variable
      ansible.builtin.debug:
        msg: "SAP_HA:        '{{ lookup('ansible.builtin.env', 'SAP_HA') }}'"    
      
    - name: Show DB_HA variable
      ansible.builtin.debug:
        msg: "DB_HA:         '{{ lookup('ansible.builtin.env', 'DB_HA') }}'"

    - name: Show DB_HA variable
      ansible.builtin.debug:
        msg: "MASTER_PW:         '{{ lookup('ansible.builtin.env', 'MASTER_PW') }}'"
    
    - name: Assign internal variables from env variables
      ansible.builtin.set_fact:
        SAPsid: "{{ lookup('env', 'SAP_SID') }}"
        DBha: "{{ lookup('env', 'SB_HA', default=false) }}"
        SAPha: "{{ lookup('env', 'SAP_HA', default=false) }}"
        SAPrelease: "{{ lookup('env', 'SAP_RELEASE') }}"
        MasterPW: "{{ lookup('env', 'MASTER_PW') }}"
      delegate_to: localhost

    - name: Show DB_HA variable
      ansible.builtin.debug:
        msg: "'{{ SAPsid }}' '{{ SAPrelease }}' '{{ SAPha }}' '{{ DBha }}' '{{ MasterPW }}'"
        
    - name: 'Copy page template to server'
      copy:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
    
    - name: 'Update J2SAP_SID with actual SAP SID'
      ansible.builtin.replace:
        path: /var/www/html/index.html
        regexp: 'J2SAP_SID'
        replace: '{{ SAP_SID }}'
